spring:
  application:
    name: cat_service

server:
  port: 0

cats:
  url: https://api.thecatapi.com/v1/images/search

eureka:

  client:
    serviceUrl:
      defaultZone: http://asyncapp-eureka:9000/eureka

  instance:
    prefer-ip-address: true
    hostname: asyncapp-eureka