spring:

  data:

    mongodb:

      host: environment-mongo
      port: 27017
      database: reactive_contracts_db
      username: reactive_user
      password: reactive_pass

server:
  port: 8081

tarantool-service:

  url: http://reactivecontracts-tarantool:8086
