FROM postgres:10.5-alpine
LABEL maintainer="Andrey Romanov <steampart@gmail.com>"

ENV POSTGRES_DB docker-db
ENV POSTGRES_USER asyncapp-user
ENV POSTGRES_PASSWORD asyncpass
ENV PGDATA /var/lib/postgresql/data/pgdata